#!/system/bin/sh

# Define the game configuration function
# Format：Game&Dirs Name | PackageName | ScriptList ( filename:args, filename:args, ...) (args are parameters passed in from stdin, which can be optional)

get_games_config() {
    echo "example | com.android.setting | script.sh:123456789"
}
